version: 2.1

jobs:
  build:
    docker:
      - image: cmig/ruby:3.1.1
        auth:
          username: cristianchirtos
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rubocop -c .rubocop.yml

workflows:
  say-hello-workflow:
    jobs:
      - build
